<a href="https://colab.research.google.com/github/vivianagonzalez203/Bootcamp-Data-Science/blob/main/02_Python/Clase_9_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy para Análisis de Datos

**Objetivo:** Dominar el uso de arreglos multidimensionales (ndarrays), operaciones vectorizadas, broadcasting y filtrado avanzado con NumPy como base para el análisis de datos masivos.

---
## Sección 1: Introducción y Arrays vs. Listas Tradicionales

### Puntos Clave:
- **¿Qué es NumPy?**: Librería fundamental para el cómputo científico en Python (*Numerical Python*).
- **Contigüidad en Memoria**: Las listas de Python son colecciones de punteros a objetos dispersos en memoria. Los `ndarray` de NumPy almacenan datos homogéneos en bloques contiguos de memoria C-contiguous.
- **Desempeño y Vectorización**: NumPy delega operaciones a bibliotecas C/Fortran altamente optimizadas (OpenBLAS/LAPACK), evitando la sobrecarga (overhead) del bucle `for` de Python.

In [ ]:
import numpy as np
import time

# Demostración de Eficiencia: Listas vs NumPy
N = 1_000_000

# 1. Uso de listas nativas de Python
lista_py = list(range(N))
start_py = time.time()
resultado_py = [x * 2 for x in lista_py]
end_py = time.time()
tiempo_py = end_py - start_py

# 2. Uso de NumPy ndarray
array_np = np.arange(N)
start_np = time.time()
resultado_np = array_np * 2
end_np = time.time()
tiempo_np = end_np - start_np

print(f"Tiempo Lista Python: {tiempo_py:.6f} segundos")
print(f"Tiempo NumPy Array:  {tiempo_np:.6f} segundos")
print(f" NumPy es {tiempo_py / tiempo_np:.2f}x más rápido.")


Tiempo Lista Python: 0.095608 segundos
Tiempo NumPy Array:  0.005529 segundos
🚀 NumPy es 17.29x más rápido.


---
## Sección 2: Creación y Manipulación de Arrays

### Puntos Clave:
- **Dimensiones**: Vector 1D (`shape: (n,)`), Matriz 2D (`shape: (filas, columnas)`).
- **Constructores Comunes**: `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`.
- **Remodelado (`.reshape()`)**: Cambia la estructura dimensional sin duplicar datos en memoria (vista vs. copia).

In [ ]:
# Creación de Arrays Básicos
vector_1d = np.array([10, 20, 30, 40, 50])
print("Vector 1D:\n", vector_1d)
print("Shape 1D:", vector_1d.shape)
print("Dtype:", vector_1d.dtype)

# Matrices Especiales
matriz_ceros = np.zeros((3, 4))
matriz_unos = np.ones((2, 3), dtype=int)
secuencia = np.arange(10, 50, 5) # inicio, fin, paso

print("\nMatriz de Ceros (3x4):\n", matriz_ceros)
print("Secuencia de números:\n", secuencia)

# Manipulación de Formas (.reshape)
matriz_2d = secuencia.reshape(4, 2)
print("\nMatriz Remodelada (4x2):\n", matriz_2d)
print("Shape 2D:", matriz_2d.shape)


Vector 1D:
 [10 20 30 40 50]
Shape 1D: (5,)
Dtype: int64

Matriz de Ceros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Secuencia de números:
 [10 15 20 25 30 35 40 45]

Matriz Remodelada (4x2):
 [[10 15]
 [20 25]
 [30 35]
 [40 45]]
Shape 2D: (4, 2)


---
## Sección 3: Operaciones Vectorizadas, Broadcasting y Estadística

### Puntos Clave:
- **Vectorización**: Aplicar operaciones matemáticas elemento a elemento sin bucles explícitos.
- **Broadcasting**: Reglas para realizar operaciones aritméticas entre arrays de diferentes dimensiones.
- **Funciones de Agregación**: Métodos numéricos como `mean()`, `std()`, `sum()`, `min()`, `max()`, especificando ejes (`axis=0` por columna, `axis=1` por fila).

In [ ]:
# Datos simulados: Calificaciones de 4 estudiantes en 3 exámenes
# Filas = Estudiantes, Columnas = Exámenes
np.random.seed(42)
notas = np.random.randint(50, 101, size=(4, 3))
print("Matriz de Notas (4x3):\n", notas)

# 1. Operación Vectorizada (Escalado de notas +5 puntos)
notas_ajustadas = notas + 5
print("\nNotas Ajustadas (+5 puntos):\n", notas_ajustadas)

# 2. Broadcasting con Vector 1D (Descuento individual por examen)
descuentos = np.array([2, 5, 0]) # 1D shape (3,)
notas_finales = notas_ajustadas - descuentos
print("\nNotas Finales tras Descuentos por Examen:\n", notas_finales)

# 3. Funciones Estadísticas
promedio_general = np.mean(notas_finales)
promedio_por_estudiante = np.mean(notas_finales, axis=1) # Por filas
promedio_por_examen = np.mean(notas_finales, axis=0)     # Por columnas

print(f"\nPromedio General del Curso: {promedio_general:.2f}")
print("Promedio por Estudiante (Fila):", promedio_por_estudiante)
print("Promedio por Examen (Columna):", promedio_por_examen)


Matriz de Notas (4x3):
 [[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]]

Notas Ajustadas (+5 puntos):
 [[93 83 69]
 [97 62 75]
 [93 73 77]
 [65 65 78]]

Notas Finales tras Descuentos por Examen:
 [[91 78 69]
 [95 57 75]
 [91 68 77]
 [63 60 78]]

Promedio General del Curso: 75.17
Promedio por Estudiante (Fila): [79.33333333 75.66666667 78.66666667 67.        ]
Promedio por Examen (Columna): [85.   65.75 74.75]


---
## Sección 4: Indexación, Slicing y Máscaras Booleanas

### Puntos Clave:
- **Slicing multidimensional**: `array[fila_inicio:fila_fin, col_inicio:col_fin]`.
- **Máscaras Booleanas**: Filtrado condicional eficiente basado en operaciones lógicas que devuelven un array de `True`/`False`.

In [ ]:
# Dataset simulado: Temperaturas registradas (°C)
temperaturas = np.array([22.5, 31.0, 18.2, 35.4, 29.8, 40.1, 15.0, 33.2])

# Slicing básico (Primeros 4 días)
print("Primeras 4 temperaturas:", temperaturas[:4])

# Máscara Booleana (Identificar olas de calor > 30°C)
mascara_calor = temperaturas > 30.0
print("\nMáscara Booleana (> 30°C):\n", mascara_calor)

# Filtrado con Máscara
dias_calurosos = temperaturas[mascara_calor]
print("Valores de Días Calurosos:\n", dias_calurosos)

# Reemplazo condicional usando la máscara
temperaturas_limpias = temperaturas.copy()
temperaturas_limpias[temperaturas_limpias > 38.0] = 38.0 # Cap a 38°C por anomalía
print("\nTemperaturas Normalizadas (Cap en 38°C):\n", temperaturas_limpias)


Primeras 4 temperaturas: [22.5 31.  18.2 35.4]

Máscara Booleana (> 30°C):
 [False  True False  True False  True False  True]
Valores de Días Calurosos:
 [31.  35.4 40.1 33.2]

Temperaturas Normalizadas (Cap en 38°C):
 [22.5 31.  18.2 35.4 29.8 38.  15.  33.2]


---
## Sección 5: Ejercicio Práctico Tipo Reto

### Reto de Análisis de Ventas:
Dado el siguiente matriz de ventas mensuales (en miles de USD) de **3 productos (filas)** a lo largo de **4 trimestres (columnas)**:

1. Encuentra el total de ventas acumulado por cada producto.
2. Aplica un incremento del 10% de impuesto solo a los trimestres 3 y 4 (columnas 2 y 3).
3. Filtra y muestra únicamente las ventas individuales que superen los 50 mil dólares en la matriz original.

In [ ]:
# Matriz de ventas (Productos x Trimestres)
ventas = np.array([
    [45, 52, 60, 38],  # Producto A
    [20, 25, 30, 35],  # Producto B
    [70, 80, 85, 90]   # Producto C
])

# --- ESCRIBE TU SOLUCIÓN AQUÍ ---

total_producto = ventas.sum(axis=1)
print("Total de ventas por producto:", total_producto)

Total de ventas por producto: [195 110 325]


In [ ]:
ventas_impuesto = ventas.astype(float).copy()
ventas_impuesto [:,2]*= 1.10
print(ventas_impuesto)

[[45.  52.  66.  38. ]
 [20.  25.  33.  35. ]
 [70.  80.  93.5 90. ]]


In [ ]:
ventas_altas = ventas[ventas >50]
print(ventas_altas)

[52 60 70 80 85 90]
